### ISSUE TITLE
Raw OCSP response for embedded pdf signatures (PADES)

### ISSUE THREAD

**Issue by cw6365** [timokoessler/easy-ocsp#2]
Hey, thanks for this easy to use library. is it possible to just get the raw response for use in PADES or is the only option as below:

```
{
  status: 'good',
  ocspUrl: 'http://r3.o.lencr.org',
  producedAt: 2024-05-19T21:11:00.000Z,
  nextUpdate: 2024-05-26T21:10:58.000Z,
  thisUpdate: 2024-05-19T21:11:00.000Z
}
```

**Comment by timokoessler** [comment]
Thank you for your suggestion. I will add the option to additionally get the raw response bytes and a separate method to get only the raw bytes.

I can't promise, but I'll probably add it tomorrow.

**Comment by timokoessler** [comment]
I added the new feature and have already released an update. You can find the new function and the new option in the docs: [ocsp.tkoessler.de](https://ocsp.tkoessler.de)

**Comment by cw6365** [comment]
@timokoessler that's great, thanks!
