### ISSUE TITLE
Bug: Uncaught ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by cw6365** [timokoessler/easy-ocsp#4]
**Describe the bug**
I started to get the following error using this library in my project..

```
Uncaught ReferenceError: fetch is not defined
    at downloadIssuerCert (lib/easy-ocsp/dist/index.js:360:15)
    at sendOCSPRequest (libecm-api-v1/lib/easy-ocsp/dist/index.js:400:31)
    at Object.getCertStatus (lib/easy-ocsp/dist/index.js:434:69)
    at REPL77:1:48
> exit
```

**To Reproduce**
var ocsp = require('easy-ocsp');
var res = await ocsp.getCertStatus(`-----BEGIN CERTIFICATE-----......')

**Additional context**
I installed node-fetch 2.6.1, imported the fetch into index.js and it worked fine.

**Comment by cw6365** [comment]
@timokoessler i'll submit a PR if this is an issue. It was actually working ok a month or two ago.

**Comment by timokoessler** [comment]
Hi, please note that this library requires at least Node.js v18 to work. What JS runtime and version are you using?

**Comment by cw6365** [comment]
@timokoessler  v18.19.0

**Comment by timokoessler** [comment]
I tested the library successfully using Node.js v18.19.0 now. Are you sure that you are using this Node.js version? The global fetch API was added in Node.js v18.0.0 and the error message shouldn't be a bug in this library.

**Comment by cw6365** [comment]
@timokoessler yep that's what im seeing with easy-ocsp -v 1.2.0.. it might be something local then, i'll look into it some more.

```
⋊> ~/S/e/l/easy-ocsp on main ⨯ NODE_PATH=./ node                                               20:17:56
Welcome to Node.js v18.19.0.
Type ".help" for more information.
> process.version
'v18.19.0'
> var ocsp = require('easy-ocsp');
undefined
> const ocspResult = await ocsp.getCertStatusByDomain('https://www.github.com');
Uncaught ReferenceError: fetch is not defined
    at downloadIssuerCert (/Users/chrisward/Sites/ecm-api-v1/lib/easy-ocsp/dist/index.js:360:15)
    at sendOCSPRequest (/Users/chrisward/Sites/ecm-api-v1/lib/easy-ocsp/dist/index.js:400:31)
    at getCertStatus (/Users/chrisward/Sites/ecm-api-v1/lib/easy-ocsp/dist/index.js:434:69)
    at Object.getCertStatusByDomain (/Users/chrisward/Sites/ecm-api-v1/lib/easy-ocsp/dist/index.js:457:10)
    at async REPL7:1:51
>
```

**Comment by timokoessler** [comment]
Did you try to reinstall Node.js / use a newer Node.js version?
Maybe you have set `--no-experimental-fetch` in the `NODE_OPTIONS` environment variable?
Really strange issue.

**Comment by cw6365** [comment]
Ah yea you're right i did have --no-experimental-fetch 🤦 sry, closing issue!
